POST http://localhost:3000/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "tiemend",
    "password": "secret"
}

###

GET http://localhost:3000/api/setup HTTP/1.1

###

GET http://localhost:3000/api/sets HTTP/1.1
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkRob25kdCBUaWVtZW4iLCJuYmYiOjE2NTE0MjIzMjksImV4cCI6MTY1MTQyNTkyOSwiaXNzIjoiaHR0cHM6Ly9sb2NhbGhvc3Q6MzAwMCIsImF1ZCI6ImxlZ29fYXBpX3VzZXJzIn0.LzPdRffWdMYCibY99Mjim_hLtsMZ7G1zqpB44_Dt2Ls
Content-Type: application/json

###

GET http://localhost:3000/api/sets/21044 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/sets/21056?includeTheme=true HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiZ2l2ZW5fbmFtZSI6IkFydGh1ciIsIm5iZiI6MTY1MDI3OTIwOCwiZXhwIjoxNjUwMjgyODA4LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo1MjgxIiwiYXVkIjoiU2tpcGFzc19BcGlfVXNlcnMifQ.EFwXhizRXyNiM_uqf9oeWmYjJv8LKjch1Fl87nUrFYc
Content-Type: application/json

###

GET http://localhost:3000/api/sets/theme/Architecture HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/sets/age/16 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/sets/price/100 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/sets HTTP/1.1
Content-Type: application/json

{
    "setNumber": 21044,
    "name": "Parijs",
    "minimalAge": "12",
    "pieces": "649",
    "price": 49.99,
    "Theme": {
        "themeId": "624ad44f4d05661bea55fb13",
        "name": "Architecture"
    }
}

###

PUT http://localhost:3000/api/sets HTTP/1.1
Content-Type: application/json

{
    "setNumber": 21044,
    "name": "Paris",
    "minimalAge": "12",
    "pieces": "649",
    "price": 59.99,
    "Theme": {
        "themeId": "624ad44f4d05661bea55fb13",
        "name": "Architecture"
    }
}

###

DELETE http://localhost:3000/api/sets/21044 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/themes HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/themes/626ed3da9f28d31220451041 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/themes HTTP/1.1
Content-Type: application/json

{
    "themeId": "624ad55f4d05661bea55fb14",
    "name": "Disney"
}

###

PUT http://localhost:3000/api/themes HTTP/1.1
Content-Type: application/json

{
    "themeId": "624ad55f4d05661bea55fb14",
    "name": "DC"
}

###

DELETE http://localhost:3000/api/themes/624ad55f4d05661bea55fb14 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/customers HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/customers/id/626ecbc40a3c37201d3a8785 HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/customers/email/aline.naert@student.vives.be HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/customers HTTP/1.1
Content-Type: application/json

{
    "name": "Tiemen Dhondt",
    "email": "tiemen.dhondt@student.vives.be"
}

###

PUT http://localhost:3000/api/customers HTTP/1.1
Content-Type: application/json

{
    "customerId": "626ed4669f28d3122045104c",
    "name": "Tiemen Dhondt",
    "email": "tiemen.dhondt@student.howest.be"
}

###

DELETE http://localhost:3000/api/customers/626ed45a9f28d3122045104b HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/orders HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/orders/id/626ed1f7f22353cc8343466e HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/orders/customerId/62610746036eb17170e200cc HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/orders/customerEmail/tiemen.dhondt2@student.howest.be HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3000/api/orders HTTP/1.1
Content-Type: application/json

{
    "Customer": {
        "customerId": "62610746036eb17170e200cc",
        "name": "Tiemen Dhondt",
        "email": "tiemen.dhondt2@student.howest.be"
    },
    "Set": {
        "setId": "624ad4f51857ee6bc28a2b58",
        "setNumber": 21042,
        "name": "Statue of Liberty",
        "minimalAge": 16,
        "pieces": 1685,
        "price": 99.99,
        "theme": {
            "themeId": "624ad44f4d05661bea55fb13",
            "name": "Architecture"
        }
    }
}

###

PUT http://localhost:3000/api/orders HTTP/1.1
Content-Type: application/json

{
    "orderId": "626113416d4bfbb38bdcb6e5",
    "Customer": {
        "customerId": "62610746036eb17170e200cc",
        "name": "Tiemen Dhondt",
        "email": "tiemen.dhondt2@student.howest.be"
    },
    "Set": {
        "setId": "624ad4f51857ee6bc28a2b58",
        "setNumber": 21042,
        "name": "Statue of Liberty",
        "minimalAge": 16,
        "pieces": 1685,
        "price": 99.99,
        "theme": {
            "themeId": "624ad44f4d05661bea55fb13",
            "name": "Architecture"
        }
    }
}

###

DELETE http://localhost:3000/api/orders/626ed4999f28d3122045104d HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3000/api/chat/test HTTP/1.1
Content-Type: application/json